### ISSUE TITLE
关于Promise catch的一段有误

### ISSUE THREAD

**Issue by zliy** [meathill/gitbook-javascript-async-tutorial#1]
正在学习promise，感谢你写的书。
发现 `02-3-promise-error.md` 里第一段代码有误，
这段：
```
new Promise( resolve => {
  setTimeout( () => {
    throw new Error('bye');
  }, 2000);
})
  .then( value => {
    console.log( value + ' world');
  })
  .catch( error => {
    console.log( 'Error: ', error.message);

// 输出：
// （2秒后）Error: bye
//     at Timeout.setTimeout [as _onTimeout] (/path/to/error.js:7:11)
//     at ontimeout (timers.js:488:11)
//     at tryOnTimeout (timers.js:323:5)
//     at Timer.listOnTimeout (timers.js:283:5)
```
缺失了一行结束括号。而且测试发现promise的catch不能处理setTimeout里的错误，
只有直接写在执行器里同步执行的thorw会被promise的catch处理
```
new Promise(resolve => {
    setTimeout(() => {
        throw new Error('bye');
    }, 2000);
})
.then(value => {
    console.log(value + ' world');
})
.catch(error => {
    console.log('promise catch')  // 添加了这一行
    console.log('Error: ', error.message);
})

// 并没有打出promise catch
```

**Comment by meathill** [comment]
嗯，这里写的确实有问题，回调函数里抛出错误实际已经是另外一个栈，所以 Promise 无法捕获。

已经修改，感谢反馈。
